### ISSUE TITLE
Fatal error: allowed mem size on vcard with photo

### ISSUE THREAD

**Issue by tvansteelandt** [nuovo/vCard-parser#14]
Getting fatal error when creating a new Vcard() that has a photo in it's data. Even 128M php memory isn't enough.
Maybe add a possibility to ignore certain vcard properties?

**Comment by pilsetnieks** [comment]
Can you please post the actual vCard somewhere? There isn't any image processing or other operations done so it isn't  obvious where the problem could be. (Other vCards with photos work just fine but with thousands of different vCard implementations there can be unforeseen issues.)

**Comment by tvansteelandt** [comment]
Hi
Thanks for answering.
Here's a public dropbox link to the test file: https://dl.dropbox.com/u/1811984/card_with_photo.vcf

I've allready made some changes to your parser, just to ignore the card photo.

**Comment by pilsetnieks** [comment]
I'm not sure about where the memory size error came from, at least on PHP 5.4 memory wasn't an issue (though it failed to parse the vCard, of course).

Anyway, it seems that the problem was with a non-standard parameter coming from Apple's Address Book (X-ABCROP-RECTANGLE) that messed up value parsing.

Please check it out now and see if the problem persists - hopefully it shouldn't.
